version: '3.1'
name: popcorn
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - db
      - redis
    environment:
      USE_MAILCATCHER: '1'
      FRONTEND_URL: 'http://localhost:4000'
      DATABASE_URI: 'postgres://popcorn:popcorn123@db/popcorn'
      REDIS_URI: 'redis://redis:6379'
      TOKEN_SECRET: 'Secret123'
      CORS_ORIGIN: 'localhost:9090'
  db:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'popcorn'
      POSTGRES_PASSWORD: 'popcorn123'
      POSTGRES_DB: 'popcorn'
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    