INSERT INTO theaters ("name", "features") VALUES
    ('Saal 1', '["Dolby Atmos","3D"]'),
    ('Saal 2', '["IMAX"]');

INSERT INTO seats ("theaterId", "displayNum", "displayX", "displayY", "flagDeluxe", "flagWheelchair") VALUES
    (1, '01', 1, 1, 'no', 'yes'),
    (1, '02', 2, 1, 'no', 'yes'),
    (1, '03', 4, 1, 'no', 'yes'),
    (1, '04', 5, 1, 'no', 'yes'),
    (1, '05', 6, 1, 'no', 'yes'),
    (1, '06', 7, 1, 'no', 'yes'),
    (1, '07', 9, 1, 'no', 'yes'),
    (1, '08', 10, 1, 'no', 'yes'),
    (1, '09', 1, 2, 'no', 'no'),
    (1, '10', 2, 2, 'no', 'yes'),
    (1, '11', 4, 2, 'no', 'yes'),
    (1, '12', 5, 2, 'no', 'no'),
    (1, '13', 6, 2, 'no', 'no'),
    (1, '14', 7, 2, 'no', 'yes'),
    (1, '15', 9, 2, 'no', 'yes'),
    (1, '16', 10, 2, 'no', 'no'),
    (1, '17', 1, 3, 'no', 'no'),
    (1, '18', 2, 3, 'no', 'yes'),
    (1, '19', 4, 3, 'no', 'yes'),
    (1, '20', 5, 3, 'no', 'no'),
    (1, '21', 6, 3, 'no', 'no'),
    (1, '22', 7, 3, 'no', 'yes'),
    (1, '23', 9, 3, 'no', 'yes'),
    (1, '24', 10, 3, 'no', 'no'),
    (1, '25', 1, 4, 'yes', 'no'),
    (1, '26', 2, 4, 'yes', 'yes'),
    (1, '27', 4, 4, 'no', 'yes'),
    (1, '28', 5, 4, 'no', 'no'),
    (1, '29', 6, 4, 'no', 'no'),
    (1, '30', 7, 4, 'no', 'yes'),
    (1, '31', 9, 4, 'yes', 'yes'),
    (1, '32', 10, 4, 'yes', 'no'),
    (1, '33', 1, 5, 'yes', 'no'),
    (1, '34', 2, 5, 'yes', 'no'),
    (1, '35', 3, 5, 'yes', 'no'),
    (1, '36', 4, 5, 'yes', 'no'),
    (1, '37', 5, 5, 'yes', 'no'),
    (1, '38', 6, 5, 'yes', 'no'),
    (1, '39', 7, 5, 'yes', 'no'),
    (1, '40', 8, 5, 'yes', 'no'),
    (1, '41', 9, 5, 'yes', 'no'),
    (1, '42', 10, 5, 'yes', 'no'),
    (2, '01', 1, 1, 'no', 'yes'),
    (2, '02', 2, 1, 'no', 'yes'),
    (2, '03', 4, 1, 'no', 'yes'),
    (2, '04', 5, 1, 'no', 'yes'),
    (2, '05', 6, 1, 'no', 'yes'),
    (2, '06', 7, 1, 'no', 'yes'),
    (2, '07', 9, 1, 'no', 'yes'),
    (2, '08', 10, 1, 'no', 'yes'),
    (2, '09', 1, 2, 'no', 'no'),
    (2, '10', 2, 2, 'no', 'yes'),
    (2, '11', 4, 2, 'no', 'yes'),
    (2, '12', 5, 2, 'no', 'no'),
    (2, '13', 6, 2, 'no', 'no'),
    (2, '14', 7, 2, 'no', 'yes'),
    (2, '15', 9, 2, 'no', 'yes'),
    (2, '16', 10, 2, 'no', 'no'),
    (2, '17', 1, 3, 'no', 'no'),
    (2, '18', 2, 3, 'no', 'yes'),
    (2, '19', 4, 3, 'no', 'yes'),
    (2, '20', 5, 3, 'no', 'no'),
    (2, '21', 6, 3, 'no', 'no'),
    (2, '22', 7, 3, 'no', 'yes'),
    (2, '23', 9, 3, 'no', 'yes'),
    (2, '24', 10, 3, 'no', 'no'),
    (2, '25', 1, 4, 'yes', 'no'),
    (2, '26', 2, 4, 'yes', 'yes'),
    (2, '27', 4, 4, 'no', 'yes'),
    (2, '28', 5, 4, 'no', 'no'),
    (2, '29', 6, 4, 'no', 'no'),
    (2, '30', 7, 4, 'no', 'yes'),
    (2, '31', 9, 4, 'yes', 'yes'),
    (2, '32', 10, 4, 'yes', 'no'),
    (2, '33', 1, 5, 'yes', 'no'),
    (2, '34', 2, 5, 'yes', 'no'),
    (2, '35', 3, 5, 'yes', 'no'),
    (2, '36', 4, 5, 'yes', 'no'),
    (2, '37', 5, 5, 'yes', 'no'),
    (2, '38', 6, 5, 'yes', 'no'),
    (2, '39', 7, 5, 'yes', 'no'),
    (2, '40', 8, 5, 'yes', 'no'),
    (2, '41', 9, 5, 'yes', 'no'),
    (2, '42', 10, 5, 'yes', 'no');

INSERT INTO movies ("name", "description", "duration", "releasedAt") VALUES
    ('Avatar: The Way of Water', 'With AVATAR: THE WAY OF WATER, the cinematic experience reaches new heights as James Cameron takes viewers back to the great world of Pandora in a spectacular and thrilling action-adventure.', 194, '2022-12-14'),
    ('M3GAN', 'Sie ist auf Freundschaft programmiert: M3GAN ist kein gewöhnliches Spielzeug, designt als beste Freundin eines Kindes und Verbündete der Eltern. Als Robotik-Expertin Gemma unerwartet zum Vormund ihrer verwaisten Nichte wird, nimmt sie den Prototyp der Hightech-Puppe mit nach Hause. Eine folgenschwere Entscheidung, denn M3GAN entwickelt einen geradezu mörderischen Beschützerinstinkt. Dass eine Puppe ihre Aufgabe so ernst nehmen wird, damit rechnet Gemma nicht einmal in ihren kühnsten Träumen, als sie diese ihrer Nichte gibt. Schließlich arbeitet sie für eine Spielzeugfirma und hat die lebensechte Puppe selbst programmiert.', 102, '2023-01-12'),
    ('I Wanna Dance with Somebody', 'I WANNA DANCE WITH SOMEBODY is the musical biopic about the late music legend Whitney Houston. In it, Naomi Ackie embodies the iconic singer on whose life and music the film is based. Directed by Kasi Lemmons and written by Oscar® nominee Anthony McCarten, the film takes audiences on an emotional, energetic journey through Houston´s career and music.', 146, '2022-12-23'),
    ('The Room', 'Johnny (Tommy Wiseau) ist ein erfolgreicher Geschäftsmann dessen Leben perfekt scheint. Er lebt in einem großen Haus mit seiner Traumfrau, Lisa (Juliette Danielle), und die beiden führen eine intensive emotionale Beziehung, die geprägt ist durch sexuelle Leidenschaft. Sein bester Freund Mark (Greg Sestero) steht im stets beiseite und soll Trautzeuge bei der geplanten Hochzeit werden. Lisa ist schwanger und das Glück scheint perfekt.', 99, '2003-06-27');

INSERT INTO users ("role", "email", "password", "nameFirst", "nameLast") VALUES
    ('admin', 'admin@popcorn.at', '$argon2id$v=19$m=65536,t=3,p=4$F33333L/YzOSsml/cg2lEQ$EsZr/o2+W4obM0TvbYX3u4/9NrcaBNNb+ilUMgUEoeM', 'Administrator', 'Administrator'),
    ('manager', 'manager@popcorn.at', '$argon2id$v=19$m=65536,t=3,p=4$1vNRmmWV2srSAzWuzvYo/A$YnaCSbkKcVPoUjNpge9SqzAdB+xuRfsBHFUthPQXgnY', 'Manager', 'Einstein');

INSERT INTO user_confirmations ("userId", "key", "confirmed", "confirmedAt") VALUES
    (1, md5(random()::text), TRUE, CURRENT_TIMESTAMP),
    (2, md5(random()::text), TRUE, CURRENT_TIMESTAMP);
